language: csharp
solution: src/INIFileParser.sln
script:
  - msbuild src/INIFileParser.sln -v:Quiet -t:Restore -t:Build -p:Configuration=Release
  - dotnet test src/IniFileParser.Tests/INIFileParser.Tests.csproj --no-build --configuration Release
mono: latest
dotnet: 2.1.3
