image: Visual Studio 2017

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

build_script:
  - ps: $vsDir = . "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath -format value
  - ps: . "$vsDir\MSBuild\15.0\Bin\amd64\MSBuild.exe" src\INIFileParser.sln -v:Quiet -t:Restore -t:Build -p:Configuration=Release

# TODO: Fix failing unit tests
test: off
#test_script:
#  - dotnet test src\IniFileParser.Tests\IniFileParser.Tests.csproj --no-build --configuration Release

artifacts:
  - path: '**\*.nupkg'
